# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from git_lab_python_sdk.paths.api_v4_groups_id_access_requests_user_id_approve.put import ApproveForUserRaw
from git_lab_python_sdk.paths.api_v4_projects_id_access_requests_user_id_approve.put import ApproveForUser0Raw
from git_lab_python_sdk.paths.api_v4_groups_id_access_requests_user_id.delete import DenyAccessToUserRaw
from git_lab_python_sdk.paths.api_v4_projects_id_access_requests_user_id.delete import DenyAccessToUser0Raw
from git_lab_python_sdk.paths.api_v4_groups_id_access_requests.get import GetListRaw
from git_lab_python_sdk.paths.api_v4_projects_id_access_requests.get import GetList0Raw
from git_lab_python_sdk.paths.api_v4_groups_id_access_requests.post import RequestAccessToGroupRaw
from git_lab_python_sdk.paths.api_v4_projects_id_access_requests.post import RequestAccessToProjectRaw


class AccessRequestsApiRaw(
    ApproveForUserRaw,
    ApproveForUser0Raw,
    DenyAccessToUserRaw,
    DenyAccessToUser0Raw,
    GetListRaw,
    GetList0Raw,
    RequestAccessToGroupRaw,
    RequestAccessToProjectRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
