# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from git_lab_python_sdk.paths.api_v4_groups_id_badges.post import AddBadgeToGroupRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges.post import AddProjectBadgeRaw
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.get import GetGroupBadgeRaw
from git_lab_python_sdk.paths.api_v4_groups_id_badges.get import GetListRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.get import GetProjectBadgeRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges.get import ListViewableByAuthenticatedUserRaw
from git_lab_python_sdk.paths.api_v4_groups_id_badges_render.get import PreviewBadgeFromGroupRaw
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.delete import RemoveFromGroupRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.delete import RemoveFromProjectRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges_render.get import RenderPreviewFromProjectRaw
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.put import UpdateGroupBadgeRaw
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.put import UpdateProjectBadgeRaw


class BadgesApiRaw(
    AddBadgeToGroupRaw,
    AddProjectBadgeRaw,
    GetGroupBadgeRaw,
    GetListRaw,
    GetProjectBadgeRaw,
    ListViewableByAuthenticatedUserRaw,
    PreviewBadgeFromGroupRaw,
    RemoveFromGroupRaw,
    RemoveFromProjectRaw,
    RenderPreviewFromProjectRaw,
    UpdateGroupBadgeRaw,
    UpdateProjectBadgeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
