# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from git_lab_python_sdk.paths.api_v4_groups_id_badges.post import AddBadgeToGroup
from git_lab_python_sdk.paths.api_v4_projects_id_badges.post import AddProjectBadge
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.get import GetGroupBadge
from git_lab_python_sdk.paths.api_v4_groups_id_badges.get import GetList
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.get import GetProjectBadge
from git_lab_python_sdk.paths.api_v4_projects_id_badges.get import ListViewableByAuthenticatedUser
from git_lab_python_sdk.paths.api_v4_groups_id_badges_render.get import PreviewBadgeFromGroup
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.delete import RemoveFromGroup
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.delete import RemoveFromProject
from git_lab_python_sdk.paths.api_v4_projects_id_badges_render.get import RenderPreviewFromProject
from git_lab_python_sdk.paths.api_v4_groups_id_badges_badge_id.put import UpdateGroupBadge
from git_lab_python_sdk.paths.api_v4_projects_id_badges_badge_id.put import UpdateProjectBadge
from git_lab_python_sdk.apis.tags.badges_api_raw import BadgesApiRaw


class BadgesApi(
    AddBadgeToGroup,
    AddProjectBadge,
    GetGroupBadge,
    GetList,
    GetProjectBadge,
    ListViewableByAuthenticatedUser,
    PreviewBadgeFromGroup,
    RemoveFromGroup,
    RemoveFromProject,
    RenderPreviewFromProject,
    UpdateGroupBadge,
    UpdateProjectBadge,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BadgesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BadgesApiRaw(api_client)
