# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches_branch.head import CheckIfExistsRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches.post import CreateBranchRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches_branch.delete import DeleteBranchRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_merged_branches.delete import DeleteMergedRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches.get import GetAllRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches_branch.get import GetSingleBranchRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches_branch_protect.put import ProtectBranchRaw
from git_lab_python_sdk.paths.api_v4_projects_id_repository_branches_branch_unprotect.put import UnprotectBranchRaw


class BranchesApiRaw(
    CheckIfExistsRaw,
    CreateBranchRaw,
    DeleteBranchRaw,
    DeleteMergedRaw,
    GetAllRaw,
    GetSingleBranchRaw,
    ProtectBranchRaw,
    UnprotectBranchRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
