# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from git_lab_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    API_V4_GROUPS_ID_BADGES_BADGE_ID = "/api/v4/groups/{id}/badges/{badge_id}"
    API_V4_GROUPS_ID_BADGES = "/api/v4/groups/{id}/badges"
    API_V4_GROUPS_ID_BADGES_RENDER = "/api/v4/groups/{id}/badges/render"
    API_V4_GROUPS_ID_ACCESS_REQUESTS_USER_ID = "/api/v4/groups/{id}/access_requests/{user_id}"
    API_V4_GROUPS_ID_ACCESS_REQUESTS_USER_ID_APPROVE = "/api/v4/groups/{id}/access_requests/{user_id}/approve"
    API_V4_GROUPS_ID_ACCESS_REQUESTS = "/api/v4/groups/{id}/access_requests"
    API_V4_PROJECTS_ID_REPOSITORY_MERGED_BRANCHES = "/api/v4/projects/{id}/repository/merged_branches"
    API_V4_PROJECTS_ID_REPOSITORY_BRANCHES_BRANCH = "/api/v4/projects/{id}/repository/branches/{branch}"
    API_V4_PROJECTS_ID_REPOSITORY_BRANCHES = "/api/v4/projects/{id}/repository/branches"
    API_V4_PROJECTS_ID_REPOSITORY_BRANCHES_BRANCH_UNPROTECT = "/api/v4/projects/{id}/repository/branches/{branch}/unprotect"
    API_V4_PROJECTS_ID_REPOSITORY_BRANCHES_BRANCH_PROTECT = "/api/v4/projects/{id}/repository/branches/{branch}/protect"
    API_V4_PROJECTS_ID_BADGES_BADGE_ID = "/api/v4/projects/{id}/badges/{badge_id}"
    API_V4_PROJECTS_ID_BADGES = "/api/v4/projects/{id}/badges"
    API_V4_PROJECTS_ID_BADGES_RENDER = "/api/v4/projects/{id}/badges/render"
    API_V4_PROJECTS_ID_ACCESS_REQUESTS_USER_ID = "/api/v4/projects/{id}/access_requests/{user_id}"
    API_V4_PROJECTS_ID_ACCESS_REQUESTS_USER_ID_APPROVE = "/api/v4/projects/{id}/access_requests/{user_id}/approve"
    API_V4_PROJECTS_ID_ACCESS_REQUESTS = "/api/v4/projects/{id}/access_requests"
    API_V4_PROJECTS_ID_ALERT_MANAGEMENT_ALERTS_ALERT_IID_METRIC_IMAGES_METRIC_IMAGE_ID = "/api/v4/projects/{id}/alert_management_alerts/{alert_iid}/metric_images/{metric_image_id}"
    API_V4_PROJECTS_ID_ALERT_MANAGEMENT_ALERTS_ALERT_IID_METRIC_IMAGES = "/api/v4/projects/{id}/alert_management_alerts/{alert_iid}/metric_images"
    API_V4_PROJECTS_ID_ALERT_MANAGEMENT_ALERTS_ALERT_IID_METRIC_IMAGES_AUTHORIZE = "/api/v4/projects/{id}/alert_management_alerts/{alert_iid}/metric_images/authorize"
    API_V4_ADMIN_BATCHED_BACKGROUND_MIGRATIONS_ID = "/api/v4/admin/batched_background_migrations/{id}"
    API_V4_ADMIN_BATCHED_BACKGROUND_MIGRATIONS = "/api/v4/admin/batched_background_migrations"
    API_V4_ADMIN_BATCHED_BACKGROUND_MIGRATIONS_ID_RESUME = "/api/v4/admin/batched_background_migrations/{id}/resume"
    API_V4_ADMIN_BATCHED_BACKGROUND_MIGRATIONS_ID_PAUSE = "/api/v4/admin/batched_background_migrations/{id}/pause"
    API_V4_ADMIN_CI_VARIABLES_KEY = "/api/v4/admin/ci/variables/{key}"
    API_V4_ADMIN_CI_VARIABLES = "/api/v4/admin/ci/variables"
    API_V4_ADMIN_DATABASES_DATABASE_NAME_DICTIONARY_TABLES_TABLE_NAME = "/api/v4/admin/databases/{database_name}/dictionary/tables/{table_name}"
    API_V4_ADMIN_CLUSTERS_CLUSTER_ID = "/api/v4/admin/clusters/{cluster_id}"
    API_V4_ADMIN_CLUSTERS_ADD = "/api/v4/admin/clusters/add"
    API_V4_ADMIN_CLUSTERS = "/api/v4/admin/clusters"
    API_V4_ADMIN_MIGRATIONS_TIMESTAMP_MARK = "/api/v4/admin/migrations/{timestamp}/mark"
    API_V4_APPLICATIONS_ID = "/api/v4/applications/{id}"
    API_V4_APPLICATIONS = "/api/v4/applications"
    API_V4_AVATAR = "/api/v4/avatar"
    API_V4_BROADCAST_MESSAGES_ID = "/api/v4/broadcast_messages/{id}"
    API_V4_BROADCAST_MESSAGES = "/api/v4/broadcast_messages"
    API_V4_BULK_IMPORTS_IMPORT_ID_ENTITIES_ENTITY_ID = "/api/v4/bulk_imports/{import_id}/entities/{entity_id}"
    API_V4_BULK_IMPORTS_IMPORT_ID_ENTITIES = "/api/v4/bulk_imports/{import_id}/entities"
    API_V4_BULK_IMPORTS_IMPORT_ID = "/api/v4/bulk_imports/{import_id}"
    API_V4_BULK_IMPORTS_ENTITIES = "/api/v4/bulk_imports/entities"
    API_V4_BULK_IMPORTS = "/api/v4/bulk_imports"
    API_V4_APPLICATION_APPEARANCE = "/api/v4/application/appearance"
    API_V4_APPLICATION_PLAN_LIMITS = "/api/v4/application/plan_limits"
    API_V4_METADATA = "/api/v4/metadata"
    API_V4_VERSION = "/api/v4/version"
    API_V4_PROJECTS_ID_JOBS = "/api/v4/projects/{id}/jobs"
    API_V4_PROJECTS_ID_JOBS_JOB_ID = "/api/v4/projects/{id}/jobs/{job_id}"
    API_V4_PROJECTS_ID_JOBS_JOB_ID_PLAY = "/api/v4/projects/{id}/jobs/{job_id}/play"
