# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class APIEntitiesPlanLimit(BaseModel):
    ci_pipeline_size: typing.Optional[int] = Field(None, alias='ci_pipeline_size')

    ci_active_jobs: typing.Optional[int] = Field(None, alias='ci_active_jobs')

    ci_project_subscriptions: typing.Optional[int] = Field(None, alias='ci_project_subscriptions')

    ci_pipeline_schedules: typing.Optional[int] = Field(None, alias='ci_pipeline_schedules')

    ci_needs_size_limit: typing.Optional[int] = Field(None, alias='ci_needs_size_limit')

    ci_registered_group_runners: typing.Optional[int] = Field(None, alias='ci_registered_group_runners')

    ci_registered_project_runners: typing.Optional[int] = Field(None, alias='ci_registered_project_runners')

    conan_max_file_size: typing.Optional[int] = Field(None, alias='conan_max_file_size')

    enforcement_limit: typing.Optional[int] = Field(None, alias='enforcement_limit')

    generic_packages_max_file_size: typing.Optional[int] = Field(None, alias='generic_packages_max_file_size')

    helm_max_file_size: typing.Optional[int] = Field(None, alias='helm_max_file_size')

    limits_history: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='limits_history')

    maven_max_file_size: typing.Optional[int] = Field(None, alias='maven_max_file_size')

    notification_limit: typing.Optional[int] = Field(None, alias='notification_limit')

    npm_max_file_size: typing.Optional[int] = Field(None, alias='npm_max_file_size')

    nuget_max_file_size: typing.Optional[int] = Field(None, alias='nuget_max_file_size')

    pipeline_hierarchy_size: typing.Optional[int] = Field(None, alias='pipeline_hierarchy_size')

    pypi_max_file_size: typing.Optional[int] = Field(None, alias='pypi_max_file_size')

    terraform_module_max_file_size: typing.Optional[int] = Field(None, alias='terraform_module_max_file_size')

    storage_size_limit: typing.Optional[int] = Field(None, alias='storage_size_limit')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
