# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CivariablesCreateNewInstanceVariableRequest(BaseModel):
    # The key of the variable. Max 255 characters
    key: str = Field(alias='key')

    # The value of a variable
    value: str = Field(alias='value')

    # Whether the variable is protected
    protected: typing.Optional[bool] = Field(None, alias='protected')

    # Whether the variable is masked
    masked: typing.Optional[bool] = Field(None, alias='masked')

    # Whether the variable will be expanded
    raw: typing.Optional[bool] = Field(None, alias='raw')

    # The type of a variable. Available types are: env_var (default) and file
    variable_type: typing.Optional[Literal["env_var", "file"]] = Field(None, alias='variable_type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
