# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class APIEntitiesBranch(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    API_Entities_Branch model
    """


    class MetaOapg:
        
        class properties:
            name = schemas.StrSchema
        
            @staticmethod
            def commit() -> typing.Type['APIEntitiesCommit']:
                return APIEntitiesCommit
            merged = schemas.BoolSchema
            protected = schemas.BoolSchema
            developers_can_push = schemas.BoolSchema
            developers_can_merge = schemas.BoolSchema
            can_push = schemas.BoolSchema
            default = schemas.BoolSchema
            web_url = schemas.StrSchema
            __annotations__ = {
                "name": name,
                "commit": commit,
                "merged": merged,
                "protected": protected,
                "developers_can_push": developers_can_push,
                "developers_can_merge": developers_can_merge,
                "can_push": can_push,
                "default": default,
                "web_url": web_url,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["commit"]) -> 'APIEntitiesCommit': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merged"]) -> MetaOapg.properties.merged: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["protected"]) -> MetaOapg.properties.protected: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["developers_can_push"]) -> MetaOapg.properties.developers_can_push: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["developers_can_merge"]) -> MetaOapg.properties.developers_can_merge: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["can_push"]) -> MetaOapg.properties.can_push: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["default"]) -> MetaOapg.properties.default: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["web_url"]) -> MetaOapg.properties.web_url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "commit", "merged", "protected", "developers_can_push", "developers_can_merge", "can_push", "default", "web_url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["commit"]) -> typing.Union['APIEntitiesCommit', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merged"]) -> typing.Union[MetaOapg.properties.merged, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["protected"]) -> typing.Union[MetaOapg.properties.protected, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["developers_can_push"]) -> typing.Union[MetaOapg.properties.developers_can_push, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["developers_can_merge"]) -> typing.Union[MetaOapg.properties.developers_can_merge, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["can_push"]) -> typing.Union[MetaOapg.properties.can_push, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["default"]) -> typing.Union[MetaOapg.properties.default, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["web_url"]) -> typing.Union[MetaOapg.properties.web_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "commit", "merged", "protected", "developers_can_push", "developers_can_merge", "can_push", "default", "web_url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        commit: typing.Union['APIEntitiesCommit', schemas.Unset] = schemas.unset,
        merged: typing.Union[MetaOapg.properties.merged, bool, schemas.Unset] = schemas.unset,
        protected: typing.Union[MetaOapg.properties.protected, bool, schemas.Unset] = schemas.unset,
        developers_can_push: typing.Union[MetaOapg.properties.developers_can_push, bool, schemas.Unset] = schemas.unset,
        developers_can_merge: typing.Union[MetaOapg.properties.developers_can_merge, bool, schemas.Unset] = schemas.unset,
        can_push: typing.Union[MetaOapg.properties.can_push, bool, schemas.Unset] = schemas.unset,
        default: typing.Union[MetaOapg.properties.default, bool, schemas.Unset] = schemas.unset,
        web_url: typing.Union[MetaOapg.properties.web_url, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'APIEntitiesBranch':
        return super().__new__(
            cls,
            *args,
            name=name,
            commit=commit,
            merged=merged,
            protected=protected,
            developers_can_push=developers_can_push,
            developers_can_merge=developers_can_merge,
            can_push=can_push,
            default=default,
            web_url=web_url,
            _configuration=_configuration,
            **kwargs,
        )

from git_lab_python_sdk.model.api_entities_commit import APIEntitiesCommit
