# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class APIEntitiesCommit(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
            id = schemas.StrSchema
            short_id = schemas.StrSchema
            created_at = schemas.DateTimeSchema
        
            @staticmethod
            def parent_ids() -> typing.Type['APIEntitiesCommitParentIds']:
                return APIEntitiesCommitParentIds
            message = schemas.StrSchema
            author_name = schemas.StrSchema
            author_email = schemas.StrSchema
            authored_date = schemas.DateTimeSchema
            committer_name = schemas.StrSchema
            committer_email = schemas.StrSchema
            committed_date = schemas.DateTimeSchema
            trailers = schemas.DictSchema
            web_url = schemas.StrSchema
            __annotations__ = {
                "title": title,
                "id": id,
                "short_id": short_id,
                "created_at": created_at,
                "parent_ids": parent_ids,
                "message": message,
                "author_name": author_name,
                "author_email": author_email,
                "authored_date": authored_date,
                "committer_name": committer_name,
                "committer_email": committer_email,
                "committed_date": committed_date,
                "trailers": trailers,
                "web_url": web_url,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["short_id"]) -> MetaOapg.properties.short_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["created_at"]) -> MetaOapg.properties.created_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parent_ids"]) -> 'APIEntitiesCommitParentIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author_name"]) -> MetaOapg.properties.author_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author_email"]) -> MetaOapg.properties.author_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authored_date"]) -> MetaOapg.properties.authored_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["committer_name"]) -> MetaOapg.properties.committer_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["committer_email"]) -> MetaOapg.properties.committer_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["committed_date"]) -> MetaOapg.properties.committed_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trailers"]) -> MetaOapg.properties.trailers: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["web_url"]) -> MetaOapg.properties.web_url: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "id", "short_id", "created_at", "parent_ids", "message", "author_name", "author_email", "authored_date", "committer_name", "committer_email", "committed_date", "trailers", "web_url", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["short_id"]) -> typing.Union[MetaOapg.properties.short_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["created_at"]) -> typing.Union[MetaOapg.properties.created_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parent_ids"]) -> typing.Union['APIEntitiesCommitParentIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author_name"]) -> typing.Union[MetaOapg.properties.author_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author_email"]) -> typing.Union[MetaOapg.properties.author_email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authored_date"]) -> typing.Union[MetaOapg.properties.authored_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["committer_name"]) -> typing.Union[MetaOapg.properties.committer_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["committer_email"]) -> typing.Union[MetaOapg.properties.committer_email, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["committed_date"]) -> typing.Union[MetaOapg.properties.committed_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trailers"]) -> typing.Union[MetaOapg.properties.trailers, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["web_url"]) -> typing.Union[MetaOapg.properties.web_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "id", "short_id", "created_at", "parent_ids", "message", "author_name", "author_email", "authored_date", "committer_name", "committer_email", "committed_date", "trailers", "web_url", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        short_id: typing.Union[MetaOapg.properties.short_id, str, schemas.Unset] = schemas.unset,
        created_at: typing.Union[MetaOapg.properties.created_at, str, datetime, schemas.Unset] = schemas.unset,
        parent_ids: typing.Union['APIEntitiesCommitParentIds', schemas.Unset] = schemas.unset,
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        author_name: typing.Union[MetaOapg.properties.author_name, str, schemas.Unset] = schemas.unset,
        author_email: typing.Union[MetaOapg.properties.author_email, str, schemas.Unset] = schemas.unset,
        authored_date: typing.Union[MetaOapg.properties.authored_date, str, datetime, schemas.Unset] = schemas.unset,
        committer_name: typing.Union[MetaOapg.properties.committer_name, str, schemas.Unset] = schemas.unset,
        committer_email: typing.Union[MetaOapg.properties.committer_email, str, schemas.Unset] = schemas.unset,
        committed_date: typing.Union[MetaOapg.properties.committed_date, str, datetime, schemas.Unset] = schemas.unset,
        trailers: typing.Union[MetaOapg.properties.trailers, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        web_url: typing.Union[MetaOapg.properties.web_url, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'APIEntitiesCommit':
        return super().__new__(
            cls,
            *args,
            title=title,
            id=id,
            short_id=short_id,
            created_at=created_at,
            parent_ids=parent_ids,
            message=message,
            author_name=author_name,
            author_email=author_email,
            authored_date=authored_date,
            committer_name=committer_name,
            committer_email=committer_email,
            committed_date=committed_date,
            trailers=trailers,
            web_url=web_url,
            _configuration=_configuration,
            **kwargs,
        )

from git_lab_python_sdk.model.api_entities_commit_parent_ids import APIEntitiesCommitParentIds
