# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class APIEntitiesProviderGcp(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            cluster_id = schemas.StrSchema
            status_name = schemas.StrSchema
            gcp_project_id = schemas.StrSchema
            zone = schemas.StrSchema
            machine_type = schemas.StrSchema
            num_nodes = schemas.StrSchema
            endpoint = schemas.StrSchema
            __annotations__ = {
                "cluster_id": cluster_id,
                "status_name": status_name,
                "gcp_project_id": gcp_project_id,
                "zone": zone,
                "machine_type": machine_type,
                "num_nodes": num_nodes,
                "endpoint": endpoint,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cluster_id"]) -> MetaOapg.properties.cluster_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status_name"]) -> MetaOapg.properties.status_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gcp_project_id"]) -> MetaOapg.properties.gcp_project_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["zone"]) -> MetaOapg.properties.zone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["machine_type"]) -> MetaOapg.properties.machine_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["num_nodes"]) -> MetaOapg.properties.num_nodes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endpoint"]) -> MetaOapg.properties.endpoint: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cluster_id", "status_name", "gcp_project_id", "zone", "machine_type", "num_nodes", "endpoint", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cluster_id"]) -> typing.Union[MetaOapg.properties.cluster_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status_name"]) -> typing.Union[MetaOapg.properties.status_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gcp_project_id"]) -> typing.Union[MetaOapg.properties.gcp_project_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["zone"]) -> typing.Union[MetaOapg.properties.zone, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["machine_type"]) -> typing.Union[MetaOapg.properties.machine_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["num_nodes"]) -> typing.Union[MetaOapg.properties.num_nodes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endpoint"]) -> typing.Union[MetaOapg.properties.endpoint, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cluster_id", "status_name", "gcp_project_id", "zone", "machine_type", "num_nodes", "endpoint", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cluster_id: typing.Union[MetaOapg.properties.cluster_id, str, schemas.Unset] = schemas.unset,
        status_name: typing.Union[MetaOapg.properties.status_name, str, schemas.Unset] = schemas.unset,
        gcp_project_id: typing.Union[MetaOapg.properties.gcp_project_id, str, schemas.Unset] = schemas.unset,
        zone: typing.Union[MetaOapg.properties.zone, str, schemas.Unset] = schemas.unset,
        machine_type: typing.Union[MetaOapg.properties.machine_type, str, schemas.Unset] = schemas.unset,
        num_nodes: typing.Union[MetaOapg.properties.num_nodes, str, schemas.Unset] = schemas.unset,
        endpoint: typing.Union[MetaOapg.properties.endpoint, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'APIEntitiesProviderGcp':
        return super().__new__(
            cls,
            *args,
            cluster_id=cluster_id,
            status_name=status_name,
            gcp_project_id=gcp_project_id,
            zone=zone,
            machine_type=machine_type,
            num_nodes=num_nodes,
            endpoint=endpoint,
            _configuration=_configuration,
            **kwargs,
        )
