# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class ApplicationModifyAppearanceRequest(
    schemas.AnyTypeSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            title = schemas.StrSchema
            description = schemas.StrSchema
            pwa_name = schemas.StrSchema
            pwa_short_name = schemas.StrSchema
            pwa_description = schemas.StrSchema
            logo = schemas.BinarySchema
            pwa_icon = schemas.BinarySchema
            header_logo = schemas.BinarySchema
            favicon = schemas.BinarySchema
            new_project_guidelines = schemas.StrSchema
            profile_image_guidelines = schemas.StrSchema
            header_message = schemas.StrSchema
            footer_message = schemas.StrSchema
            message_background_color = schemas.StrSchema
            message_font_color = schemas.StrSchema
            email_header_and_footer_enabled = schemas.BoolSchema
            __annotations__ = {
                "title": title,
                "description": description,
                "pwa_name": pwa_name,
                "pwa_short_name": pwa_short_name,
                "pwa_description": pwa_description,
                "logo": logo,
                "pwa_icon": pwa_icon,
                "header_logo": header_logo,
                "favicon": favicon,
                "new_project_guidelines": new_project_guidelines,
                "profile_image_guidelines": profile_image_guidelines,
                "header_message": header_message,
                "footer_message": footer_message,
                "message_background_color": message_background_color,
                "message_font_color": message_font_color,
                "email_header_and_footer_enabled": email_header_and_footer_enabled,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pwa_name"]) -> MetaOapg.properties.pwa_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pwa_short_name"]) -> MetaOapg.properties.pwa_short_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pwa_description"]) -> MetaOapg.properties.pwa_description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["logo"]) -> MetaOapg.properties.logo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pwa_icon"]) -> MetaOapg.properties.pwa_icon: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["header_logo"]) -> MetaOapg.properties.header_logo: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["favicon"]) -> MetaOapg.properties.favicon: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["new_project_guidelines"]) -> MetaOapg.properties.new_project_guidelines: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profile_image_guidelines"]) -> MetaOapg.properties.profile_image_guidelines: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["header_message"]) -> MetaOapg.properties.header_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["footer_message"]) -> MetaOapg.properties.footer_message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message_background_color"]) -> MetaOapg.properties.message_background_color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message_font_color"]) -> MetaOapg.properties.message_font_color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email_header_and_footer_enabled"]) -> MetaOapg.properties.email_header_and_footer_enabled: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["title", "description", "pwa_name", "pwa_short_name", "pwa_description", "logo", "pwa_icon", "header_logo", "favicon", "new_project_guidelines", "profile_image_guidelines", "header_message", "footer_message", "message_background_color", "message_font_color", "email_header_and_footer_enabled", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pwa_name"]) -> typing.Union[MetaOapg.properties.pwa_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pwa_short_name"]) -> typing.Union[MetaOapg.properties.pwa_short_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pwa_description"]) -> typing.Union[MetaOapg.properties.pwa_description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["logo"]) -> typing.Union[MetaOapg.properties.logo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pwa_icon"]) -> typing.Union[MetaOapg.properties.pwa_icon, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["header_logo"]) -> typing.Union[MetaOapg.properties.header_logo, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["favicon"]) -> typing.Union[MetaOapg.properties.favicon, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["new_project_guidelines"]) -> typing.Union[MetaOapg.properties.new_project_guidelines, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profile_image_guidelines"]) -> typing.Union[MetaOapg.properties.profile_image_guidelines, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["header_message"]) -> typing.Union[MetaOapg.properties.header_message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["footer_message"]) -> typing.Union[MetaOapg.properties.footer_message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message_background_color"]) -> typing.Union[MetaOapg.properties.message_background_color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message_font_color"]) -> typing.Union[MetaOapg.properties.message_font_color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email_header_and_footer_enabled"]) -> typing.Union[MetaOapg.properties.email_header_and_footer_enabled, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["title", "description", "pwa_name", "pwa_short_name", "pwa_description", "logo", "pwa_icon", "header_logo", "favicon", "new_project_guidelines", "profile_image_guidelines", "header_message", "footer_message", "message_background_color", "message_font_color", "email_header_and_footer_enabled", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        pwa_name: typing.Union[MetaOapg.properties.pwa_name, str, schemas.Unset] = schemas.unset,
        pwa_short_name: typing.Union[MetaOapg.properties.pwa_short_name, str, schemas.Unset] = schemas.unset,
        pwa_description: typing.Union[MetaOapg.properties.pwa_description, str, schemas.Unset] = schemas.unset,
        logo: typing.Union[MetaOapg.properties.logo, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        pwa_icon: typing.Union[MetaOapg.properties.pwa_icon, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        header_logo: typing.Union[MetaOapg.properties.header_logo, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        favicon: typing.Union[MetaOapg.properties.favicon, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        new_project_guidelines: typing.Union[MetaOapg.properties.new_project_guidelines, str, schemas.Unset] = schemas.unset,
        profile_image_guidelines: typing.Union[MetaOapg.properties.profile_image_guidelines, str, schemas.Unset] = schemas.unset,
        header_message: typing.Union[MetaOapg.properties.header_message, str, schemas.Unset] = schemas.unset,
        footer_message: typing.Union[MetaOapg.properties.footer_message, str, schemas.Unset] = schemas.unset,
        message_background_color: typing.Union[MetaOapg.properties.message_background_color, str, schemas.Unset] = schemas.unset,
        message_font_color: typing.Union[MetaOapg.properties.message_font_color, str, schemas.Unset] = schemas.unset,
        email_header_and_footer_enabled: typing.Union[MetaOapg.properties.email_header_and_footer_enabled, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicationModifyAppearanceRequest':
        return super().__new__(
            cls,
            *args,
            title=title,
            description=description,
            pwa_name=pwa_name,
            pwa_short_name=pwa_short_name,
            pwa_description=pwa_description,
            logo=logo,
            pwa_icon=pwa_icon,
            header_logo=header_logo,
            favicon=favicon,
            new_project_guidelines=new_project_guidelines,
            profile_image_guidelines=profile_image_guidelines,
            header_message=header_message,
            footer_message=footer_message,
            message_background_color=message_background_color,
            message_font_color=message_font_color,
            email_header_and_footer_enabled=email_header_and_footer_enabled,
            _configuration=_configuration,
            **kwargs,
        )
