# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class BroadcastmessagesUpdateMessageRequest(
    schemas.AnyTypeSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            message = schemas.StrSchema
            starts_at = schemas.DateTimeSchema
            ends_at = schemas.DateTimeSchema
            color = schemas.StrSchema
            font = schemas.StrSchema
            
            
            class target_access_levels(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.EnumBase,
                        schemas.Int32Schema
                    ):
                    
                    
                        class MetaOapg:
                            format = 'int32'
                            enum_value_to_name = {
                                10: "POSITIVE_10",
                                20: "POSITIVE_20",
                                30: "POSITIVE_30",
                                40: "POSITIVE_40",
                                50: "POSITIVE_50",
                            }
                        
                        @schemas.classproperty
                        def POSITIVE_10(cls):
                            return cls(10)
                        
                        @schemas.classproperty
                        def POSITIVE_20(cls):
                            return cls(20)
                        
                        @schemas.classproperty
                        def POSITIVE_30(cls):
                            return cls(30)
                        
                        @schemas.classproperty
                        def POSITIVE_40(cls):
                            return cls(40)
                        
                        @schemas.classproperty
                        def POSITIVE_50(cls):
                            return cls(50)
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'target_access_levels':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            target_path = schemas.StrSchema
            
            
            class broadcast_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "banner": "BANNER",
                        "notification": "NOTIFICATION",
                    }
                
                @schemas.classproperty
                def BANNER(cls):
                    return cls("banner")
                
                @schemas.classproperty
                def NOTIFICATION(cls):
                    return cls("notification")
            dismissable = schemas.BoolSchema
            __annotations__ = {
                "message": message,
                "starts_at": starts_at,
                "ends_at": ends_at,
                "color": color,
                "font": font,
                "target_access_levels": target_access_levels,
                "target_path": target_path,
                "broadcast_type": broadcast_type,
                "dismissable": dismissable,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["starts_at"]) -> MetaOapg.properties.starts_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ends_at"]) -> MetaOapg.properties.ends_at: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["color"]) -> MetaOapg.properties.color: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["font"]) -> MetaOapg.properties.font: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["target_access_levels"]) -> MetaOapg.properties.target_access_levels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["target_path"]) -> MetaOapg.properties.target_path: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["broadcast_type"]) -> MetaOapg.properties.broadcast_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dismissable"]) -> MetaOapg.properties.dismissable: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["message", "starts_at", "ends_at", "color", "font", "target_access_levels", "target_path", "broadcast_type", "dismissable", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["starts_at"]) -> typing.Union[MetaOapg.properties.starts_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ends_at"]) -> typing.Union[MetaOapg.properties.ends_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["color"]) -> typing.Union[MetaOapg.properties.color, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["font"]) -> typing.Union[MetaOapg.properties.font, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["target_access_levels"]) -> typing.Union[MetaOapg.properties.target_access_levels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["target_path"]) -> typing.Union[MetaOapg.properties.target_path, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["broadcast_type"]) -> typing.Union[MetaOapg.properties.broadcast_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dismissable"]) -> typing.Union[MetaOapg.properties.dismissable, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["message", "starts_at", "ends_at", "color", "font", "target_access_levels", "target_path", "broadcast_type", "dismissable", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        starts_at: typing.Union[MetaOapg.properties.starts_at, str, datetime, schemas.Unset] = schemas.unset,
        ends_at: typing.Union[MetaOapg.properties.ends_at, str, datetime, schemas.Unset] = schemas.unset,
        color: typing.Union[MetaOapg.properties.color, str, schemas.Unset] = schemas.unset,
        font: typing.Union[MetaOapg.properties.font, str, schemas.Unset] = schemas.unset,
        target_access_levels: typing.Union[MetaOapg.properties.target_access_levels, list, tuple, schemas.Unset] = schemas.unset,
        target_path: typing.Union[MetaOapg.properties.target_path, str, schemas.Unset] = schemas.unset,
        broadcast_type: typing.Union[MetaOapg.properties.broadcast_type, str, schemas.Unset] = schemas.unset,
        dismissable: typing.Union[MetaOapg.properties.dismissable, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BroadcastmessagesUpdateMessageRequest':
        return super().__new__(
            cls,
            *args,
            message=message,
            starts_at=starts_at,
            ends_at=ends_at,
            color=color,
            font=font,
            target_access_levels=target_access_levels,
            target_path=target_path,
            broadcast_type=broadcast_type,
            dismissable=dismissable,
            _configuration=_configuration,
            **kwargs,
        )
