# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from git_lab_python_sdk import schemas  # noqa: F401


class ClustersAddExistingKubernetesInstanceClusterRequest(
    schemas.AnyTypeSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "platform_kubernetes_attributes[api_url]",
            "name",
            "platform_kubernetes_attributes[token]",
        }
        
        class properties:
            name = schemas.StrSchema
            platform_kubernetes_attributes_api_url = schemas.StrSchema
            platform_kubernetes_attributes_token = schemas.StrSchema
            enabled = schemas.BoolSchema
            environment_scope = schemas.StrSchema
            namespace_per_environment = schemas.BoolSchema
            domain = schemas.StrSchema
            management_project_id = schemas.Int32Schema
            managed = schemas.BoolSchema
            platform_kubernetes_attributes_ca_cert = schemas.StrSchema
            platform_kubernetes_attributes_namespace = schemas.StrSchema
            
            
            class platform_kubernetes_attributes_authorization_type(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def UNKNOWN_AUTHORIZATION(cls):
                    return cls("unknown_authorization")
                
                @schemas.classproperty
                def RBAC(cls):
                    return cls("rbac")
                
                @schemas.classproperty
                def ABAC(cls):
                    return cls("abac")
            __annotations__ = {
                "name": name,
                "platform_kubernetes_attributes[api_url]": platform_kubernetes_attributes_api_url,
                "platform_kubernetes_attributes[token]": platform_kubernetes_attributes_token,
                "enabled": enabled,
                "environment_scope": environment_scope,
                "namespace_per_environment": namespace_per_environment,
                "domain": domain,
                "management_project_id": management_project_id,
                "managed": managed,
                "platform_kubernetes_attributes[ca_cert]": platform_kubernetes_attributes_ca_cert,
                "platform_kubernetes_attributes[namespace]": platform_kubernetes_attributes_namespace,
                "platform_kubernetes_attributes[authorization_type]": platform_kubernetes_attributes_authorization_type,
            }

    
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["platform_kubernetes_attributes[api_url]"]) -> MetaOapg.properties.platform_kubernetes_attributes_api_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["platform_kubernetes_attributes[token]"]) -> MetaOapg.properties.platform_kubernetes_attributes_token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enabled"]) -> MetaOapg.properties.enabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["environment_scope"]) -> MetaOapg.properties.environment_scope: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["namespace_per_environment"]) -> MetaOapg.properties.namespace_per_environment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain"]) -> MetaOapg.properties.domain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["management_project_id"]) -> MetaOapg.properties.management_project_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["managed"]) -> MetaOapg.properties.managed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["platform_kubernetes_attributes[ca_cert]"]) -> MetaOapg.properties.platform_kubernetes_attributes_ca_cert: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["platform_kubernetes_attributes[namespace]"]) -> MetaOapg.properties.platform_kubernetes_attributes_namespace: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["platform_kubernetes_attributes[authorization_type]"]) -> MetaOapg.properties.platform_kubernetes_attributes_authorization_type: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "platform_kubernetes_attributes[api_url]", "platform_kubernetes_attributes[token]", "enabled", "environment_scope", "namespace_per_environment", "domain", "management_project_id", "managed", "platform_kubernetes_attributes[ca_cert]", "platform_kubernetes_attributes[namespace]", "platform_kubernetes_attributes[authorization_type]", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["platform_kubernetes_attributes[api_url]"]) -> MetaOapg.properties.platform_kubernetes_attributes_api_url: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["platform_kubernetes_attributes[token]"]) -> MetaOapg.properties.platform_kubernetes_attributes_token: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enabled"]) -> typing.Union[MetaOapg.properties.enabled, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["environment_scope"]) -> typing.Union[MetaOapg.properties.environment_scope, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["namespace_per_environment"]) -> typing.Union[MetaOapg.properties.namespace_per_environment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain"]) -> typing.Union[MetaOapg.properties.domain, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["management_project_id"]) -> typing.Union[MetaOapg.properties.management_project_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["managed"]) -> typing.Union[MetaOapg.properties.managed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["platform_kubernetes_attributes[ca_cert]"]) -> typing.Union[MetaOapg.properties.platform_kubernetes_attributes_ca_cert, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["platform_kubernetes_attributes[namespace]"]) -> typing.Union[MetaOapg.properties.platform_kubernetes_attributes_namespace, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["platform_kubernetes_attributes[authorization_type]"]) -> typing.Union[MetaOapg.properties.platform_kubernetes_attributes_authorization_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "platform_kubernetes_attributes[api_url]", "platform_kubernetes_attributes[token]", "enabled", "environment_scope", "namespace_per_environment", "domain", "management_project_id", "managed", "platform_kubernetes_attributes[ca_cert]", "platform_kubernetes_attributes[namespace]", "platform_kubernetes_attributes[authorization_type]", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        enabled: typing.Union[MetaOapg.properties.enabled, bool, schemas.Unset] = schemas.unset,
        environment_scope: typing.Union[MetaOapg.properties.environment_scope, str, schemas.Unset] = schemas.unset,
        namespace_per_environment: typing.Union[MetaOapg.properties.namespace_per_environment, bool, schemas.Unset] = schemas.unset,
        domain: typing.Union[MetaOapg.properties.domain, str, schemas.Unset] = schemas.unset,
        management_project_id: typing.Union[MetaOapg.properties.management_project_id, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        managed: typing.Union[MetaOapg.properties.managed, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ClustersAddExistingKubernetesInstanceClusterRequest':
        return super().__new__(
            cls,
            *args,
            name=name,
            enabled=enabled,
            environment_scope=environment_scope,
            namespace_per_environment=namespace_per_environment,
            domain=domain,
            management_project_id=management_project_id,
            managed=managed,
            _configuration=_configuration,
            **kwargs,
        )
