# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from git_lab_python_sdk.type.api_entities_platform_kubernetes import APIEntitiesPlatformKubernetes
from git_lab_python_sdk.type.api_entities_project_identity import APIEntitiesProjectIdentity
from git_lab_python_sdk.type.api_entities_provider_gcp import APIEntitiesProviderGcp
from git_lab_python_sdk.type.api_entities_user_basic import APIEntitiesUserBasic

class RequiredAPIEntitiesCluster(TypedDict):
    pass

class OptionalAPIEntitiesCluster(TypedDict, total=False):
    id: str

    name: str

    created_at: str

    domain: str

    enabled: str

    managed: str

    provider_type: str

    platform_type: str

    environment_scope: str

    cluster_type: str

    namespace_per_environment: str

    user: APIEntitiesUserBasic

    platform_kubernetes: APIEntitiesPlatformKubernetes

    provider_gcp: APIEntitiesProviderGcp

    management_project: APIEntitiesProjectIdentity

class APIEntitiesCluster(RequiredAPIEntitiesCluster, OptionalAPIEntitiesCluster):
    pass
