# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from git_lab_python_sdk.type.api_entities_commit import APIEntitiesCommit
from git_lab_python_sdk.type.api_entities_job_artifacts import APIEntitiesJobArtifacts
from git_lab_python_sdk.type.api_entities_job_project import APIEntitiesJobProject
from git_lab_python_sdk.type.api_entities_user_basic import APIEntitiesUserBasic

class RequiredAPIEntitiesJob(TypedDict):
    pass

class OptionalAPIEntitiesJob(TypedDict, total=False):
    # The ID of the job
    id: int

    # The name of the job
    name: str

    # The current status of the job
    status: str

    # The stage of the job in the CI/CD pipeline
    stage: str

    # The creation time of the job
    created_at: datetime

    # The start time of the job
    started_at: datetime

    # The finish time of the job
    finished_at: datetime

    commit: APIEntitiesCommit

    # Indicates if the job is archived
    archived: bool

    # Indicates if the job is allowed to fail
    allow_failure: bool

    # The time when the job was erased, if applicable
    erased_at: datetime

    # The duration of the job in seconds
    duration: int

    # The duration the job was queued before execution, in seconds
    queued_duration: typing.Union[int, float]

    # The reference for the job
    ref: str

    artifacts: APIEntitiesJobArtifacts

    # Indicates if the job is tagged
    tag: bool

    # The URL for accessing the job in the web interface
    web_url: str

    project: APIEntitiesJobProject

    user: APIEntitiesUserBasic

class APIEntitiesJob(RequiredAPIEntitiesJob, OptionalAPIEntitiesJob):
    pass
