# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAPIEntitiesPlanLimit(TypedDict):
    pass

class OptionalAPIEntitiesPlanLimit(TypedDict, total=False):
    ci_pipeline_size: int

    ci_active_jobs: int

    ci_project_subscriptions: int

    ci_pipeline_schedules: int

    ci_needs_size_limit: int

    ci_registered_group_runners: int

    ci_registered_project_runners: int

    conan_max_file_size: int

    enforcement_limit: int

    generic_packages_max_file_size: int

    helm_max_file_size: int

    limits_history: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    maven_max_file_size: int

    notification_limit: int

    npm_max_file_size: int

    nuget_max_file_size: int

    pipeline_hierarchy_size: int

    pypi_max_file_size: int

    terraform_module_max_file_size: int

    storage_size_limit: int

class APIEntitiesPlanLimit(RequiredAPIEntitiesPlanLimit, OptionalAPIEntitiesPlanLimit):
    pass
