# coding: utf-8

"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredClustersUpdateInstanceClusterRequest(TypedDict):
    pass

class OptionalClustersUpdateInstanceClusterRequest(TypedDict, total=False):
    # Cluster name
    name: str

    # Enable or disable Gitlab's connection to your Kubernetes cluster
    enabled: bool

    # The associated environment to the cluster
    environment_scope: str

    # Deploy each environment to a separate Kubernetes namespace
    namespace_per_environment: bool

    # Cluster base domain
    domain: str

    # The ID of the management project
    management_project_id: int

    # Determines if GitLab will manage namespaces and service accounts for this cluster
    managed: bool

    # URL to access the Kubernetes API
    platform_kubernetes_attributes[api_url]: str

    # Token to authenticate against Kubernetes
    platform_kubernetes_attributes[token]: str

    # TLS certificate (needed if API is using a self-signed TLS certificate)
    platform_kubernetes_attributes[ca_cert]: str

    # Unique namespace related to Project
    platform_kubernetes_attributes[namespace]: str

class ClustersUpdateInstanceClusterRequest(RequiredClustersUpdateInstanceClusterRequest, OptionalClustersUpdateInstanceClusterRequest):
    pass
