# coding: utf-8
"""
    GitLab API

    An OpenAPI definition for the GitLab REST API. Few API resources or endpoints are currently included. The intent is to expand this to match the entire Markdown documentation of the API: <https://docs.gitlab.com/ee/api/>. Contributions are welcome.  When viewing this on gitlab.com, you can test API calls directly from the browser against the `gitlab.com` instance, if you are logged in. The feature uses the current [GitLab session cookie](https://docs.gitlab.com/ee/api/index.html#session-cookie), so each request is made using your account.  Instructions for using this tool can be found in [Interactive API Documentation](https://docs.gitlab.com/ee/api/openapi/openapi_interactive.html) 

    The version of the OpenAPI document: v4
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from git_lab_python_sdk.client_custom import ClientCustom
from git_lab_python_sdk.configuration import Configuration
from git_lab_python_sdk.api_client import ApiClient
from git_lab_python_sdk.type_util import copy_signature
from git_lab_python_sdk.apis.tags.access_requests_api import AccessRequestsApi
from git_lab_python_sdk.apis.tags.admin_api import AdminApi
from git_lab_python_sdk.apis.tags.alert_management_api import AlertManagementApi
from git_lab_python_sdk.apis.tags.application_api import ApplicationApi
from git_lab_python_sdk.apis.tags.applications_api import ApplicationsApi
from git_lab_python_sdk.apis.tags.avatar_api import AvatarApi
from git_lab_python_sdk.apis.tags.badges_api import BadgesApi
from git_lab_python_sdk.apis.tags.batched_background_migrations_api import BatchedBackgroundMigrationsApi
from git_lab_python_sdk.apis.tags.branches_api import BranchesApi
from git_lab_python_sdk.apis.tags.broadcast_messages_api import BroadcastMessagesApi
from git_lab_python_sdk.apis.tags.bulk_imports_api import BulkImportsApi
from git_lab_python_sdk.apis.tags.ci_variables_api import CiVariablesApi
from git_lab_python_sdk.apis.tags.clusters_api import ClustersApi
from git_lab_python_sdk.apis.tags.jobs_api import JobsApi
from git_lab_python_sdk.apis.tags.metadata_api import MetadataApi
from git_lab_python_sdk.apis.tags.migrations_api import MigrationsApi
from git_lab_python_sdk.apis.tags.plan_limits_api import PlanLimitsApi



class GitLab(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.access_requests: AccessRequestsApi = AccessRequestsApi(api_client)
        self.admin: AdminApi = AdminApi(api_client)
        self.alert_management: AlertManagementApi = AlertManagementApi(api_client)
        self.application: ApplicationApi = ApplicationApi(api_client)
        self.applications: ApplicationsApi = ApplicationsApi(api_client)
        self.avatar: AvatarApi = AvatarApi(api_client)
        self.badges: BadgesApi = BadgesApi(api_client)
        self.batched_background_migrations: BatchedBackgroundMigrationsApi = BatchedBackgroundMigrationsApi(api_client)
        self.branches: BranchesApi = BranchesApi(api_client)
        self.broadcast_messages: BroadcastMessagesApi = BroadcastMessagesApi(api_client)
        self.bulk_imports: BulkImportsApi = BulkImportsApi(api_client)
        self.ci_variables: CiVariablesApi = CiVariablesApi(api_client)
        self.clusters: ClustersApi = ClustersApi(api_client)
        self.jobs: JobsApi = JobsApi(api_client)
        self.metadata: MetadataApi = MetadataApi(api_client)
        self.migrations: MigrationsApi = MigrationsApi(api_client)
        self.plan_limits: PlanLimitsApi = PlanLimitsApi(api_client)
