from git_lab_python_sdk.paths.api_v4_projects_id_alert_management_alerts_alert_iid_metric_images_metric_image_id.put import ApiForput
from git_lab_python_sdk.paths.api_v4_projects_id_alert_management_alerts_alert_iid_metric_images_metric_image_id.delete import ApiFordelete


class ApiV4ProjectsIdAlertManagementAlertsAlertIidMetricImagesMetricImageId(
    ApiForput,
    ApiFordelete,
):
    pass
